steps:
  # pull the container image for cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull asia.gcr.io/nm-prod-global-cw-mi/mi-console-front:v2 || exit 0']

  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'asia.gcr.io/nm-prod-global-cw-mi/mi-console-front:v2',
      '-t', 'asia.gcr.io/nm-prod-global-cw-mi/mi-console-front:v2_$SHORT_SHA',
      '--cache-from', 'asia.gcr.io/nm-prod-global-cw-mi/mi-console-front:v2',
      '-f', 'Dockerfile.cloud.dev',
      '.'
    ]

  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/nm-prod-global-cw-mi/mi-console-front:v2']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy', 'mi-console-front-v2',
      '--image', 'asia.gcr.io/nm-prod-global-cw-mi/mi-console-front:v2',
      '--region', 'asia-northeast1',
      '--revision-suffix', '$SHORT_SHA'
    ]

# Specific Worker Pool
options:
  pool:
    name: 'projects/nm-prod-global-cw-mi/locations/asia-northeast3/workerPools/mi-builder-pool'

images:
 - 'asia.gcr.io/nm-prod-global-cw-mi/mi-console-front:v2'
 - 'asia.gcr.io/nm-prod-global-cw-mi/mi-console-front:v2_$SHORT_SHA'

timeout: 900s
