FROM asia.gcr.io/nm-prod-global-cw-mi/ubuntu-1804-jdk11:v1

RUN apt update
RUN apt install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
RUN bash /tmp/nodesource_setup.sh
RUN apt install -y nodejs

COPY . /mi-console-front
WORKDIR /mi-console-front

RUN npm i -g yarn
# coway망에서 수행시, 보안문제로 인해 "Request Error: self-signed certificate in certificate chain" 발생
RUN yarn set version berry
RUN yarn install
RUN yarn workspace mi build

EXPOSE 3000

ENTRYPOINT ["yarn", "start:mi"]
