export default {
  home: 'Home',
  report: '리포트',
  research: '시장 현황',
  summary: 'Executive Summary',
  marketShare: '시장 점유율(M/S)',
  salesVolume: '시판 판매량',
  brandAwareness: '브랜드 인지도',
  account: '계정 및 판매',
  status: '계정',
  combination: '계정 보유 조합',
  customer: '고객',
  warriorSales: '전사 판매',
  salesOrganization: '조직별 판매',
  marketing: '마케팅',
  costsEfficiency: '마케팅 비용 및 효율',
  atl: 'ATL',
  keywordAnalysis: '키워드 분석',
  management: '관리',
  administrator: 'Administrator',
  user: 'User',
  digital: '디지털',
};
